### ISSUE TITLE
Exclude Fly Imaginal disc growth factor genes from PANTHER:PTN000126545 node

### ISSUE THREAD

**Issue by phanivg** [pantherdb/Helpdesk#16]
Fly Imaginal disc growth factor genes (Idgf1-Idgf6) are Chitinase-like family members. These proteins were given chitinase activity (GO:0004568) based on PANTHER:PTN000126545 node, but PMID:18342251 suggests that fly Idgf6 (FBgn0013763 / Q23997) lacks the critical residue required for chitinase activity. 
Human orthologs CHI3L1 and CHI3L2 are also suggested to lack chitinase activity.
Can you please exclude propogation by PAINT from this node to these following FlyBase members.

FLYBASE_ID	SYMBOL	UUNIPROT_ID
FBgn0020416	Idgf1	Q8MM24
FBgn0020415	Idgf2	Q9V3D4
FBgn0020414	Idgf3	Q8MLZ7
FBgn0026415	Idgf4	Q9W303
FBgn0064237	Idgf5	Q8T0R7
FBgn0013763	Idgf6	Q23997

@hattrill

**Comment by hattrill** [comment]
Hi @phanivg  I think that this should be on the annotation tracker. Could you close this and move it there. Thanks.
