### ISSUE TITLE
Write PTHR-to-fam_name lookup file generator for .arbre headers

### ISSUE THREAD

**Issue by dustine32** [pantherdb/Helpdesk#2]
Needed to help with this ticket:
https://github.com/geneontology/amigo/issues/532

Basically, get the panther family name for each book. Ex:
```
NAME=PHOSPHOSERINE PHOSPHATASE
```

**Comment by dustine32** [comment]
@mugitty came up with the lookup query:
```
select distinct c.accession, c.name from classification c where  c.depth = 5 and c.CLASSIFICATION_VERSION_SID = 24 and c.obsolescence_date is null order by c.accession;
```

**Comment by kltm** [comment]
@dustine32 I forget where we stand on this. Is this ticket still active, or is it defunct and I'm rewriting a bit to do it at our end?

**Comment by dustine32** [comment]
@kltm Rats. I shoulda updated this ticket too. https://github.com/geneontology/amigo/issues/532#issuecomment-416738423

So it turns out there's a PTHR family name lookup file already created for version 13.1 here:
http://data.pantherdb.org/PANTHER13.1/globals/names.tab

If you could use this in combo with the `.tree` files to construct the `.arbre` files on your side that might work? Let me know if there's any weirdness with this file as I didn't generate it myself. Thanks!

**Comment by kltm** [comment]
Thank @dustine32 
Now duplicated on  geneontology/amigo#532

**Comment by kltm** [comment]
@dustine32 Feel free to close this (I don't have permissions).

**Comment by dustine32** [comment]
Sweet, thanks @kltm !
