### ISSUE TITLE
Review PTHR13345 - MED10

### ISSUE THREAD

**Issue by pgaudet** [pantherdb/Helpdesk#29]
Hello, 

Review PTHR13345  (MED10) has at least 2 nodes that seem suspicious: 
* PTN000331275 (UXT)
* PTN001000521
Sequences are quite divergent, and MED10 orthologs are spreadout through the family. 

At least 4 annotation disputes were raised concerning this family: 
https://github.com/geneontology/go-annotation/issues/3546 (NOTs not forward tracked reported by @dustine32 )
https://github.com/geneontology/go-annotation/issues/3507
https://github.com/geneontology/go-annotation/issues/3315
https://github.com/geneontology/go-annotation/issues/2463

Thanks, Pascale

**Comment by huaiyumi** [comment]
The PTN000331275 NOT annotation was fixed (see https://github.com/pantherdb/db-PAINT/issues/29).
For PTN001000521, no annotations are propagated to the node.
The question about whether these two nodes belong to the tree is not a PAINT issue, but rather a tree building issue. We have gone through the pruning process in the past. It caused as much problem, if not more, as leaving them in the same family. We may just have to live with it.
