### ISSUE TITLE
Create a top-level compressed download for easy data access (enhancement)

### ISSUE THREAD

**Issue by kltm** [pantherdb/Helpdesk#3]
Currently, if one wants to download all or part of the PANTHER data to use as a pipeline input, one must "manually" crawl http://data.pantherdb.org/PANTHER13.1/books . Given the size of PANTHER and the inherent latency of HTTP, this process can take many hours.

I would suggest a high-level file, maybe library.tar.gz at the top level of books, that contains all of the data below in a single easy-to-use form that can be quickly downloaded. This in important for use cases like https://github.com/geneontology/amigo/issues/532 , where we will be bringing PANTHER regularly in to an external pipeline that runs on the order of hours.

**Comment by dustine32** [comment]
http://data.pantherdb.org/PANTHER13.1/globals/tree_files.tar.gz

@kltm Here's the 27MB tarball containing the tree files (PTHR#####.tree) and the names.tab file. Let me know if the download speed is still slow. Thanks!

**Comment by kltm** [comment]
Cheers! I can now download what we need in 0.3s--a rather significant improvement.
Will this now be part of the standard release? If you wanted to present this as a general speed-up method, a tarball of the whole shebang might be nice as well.

**Comment by dustine32** [comment]
@kltm Finally! I have generated the `tree_files.tar.gz` for Panther version 14.1. Whenever you'd like to test it, it's available here:

http://data.pantherdb.org/PANTHER14.1/globals/tree_files.tar.gz

**Comment by dustine32** [comment]
Actually @kltm, I just realized that I hadn't yet applied my fix for https://github.com/geneontology/amigo/issues/546 to these tree files:
```
$ grep DROME tree_files/* | head
tree_files/PTHR10003.tree:AN55:DROME|Gene=Dmel_CG17753|UniProtKB=E1JH26;
tree_files/PTHR10003.tree:AN305:DROME|FlyBase=FBgn0039386|UniProtKB=Q9VBK8;
tree_files/PTHR10003.tree:AN309:DROME|FlyBase=FBgn0033631|UniProtKB=Q7JR71;
tree_files/PTHR10003.tree:AN310:DROME|FlyBase=FBgn0003462|UniProtKB=P61851;
tree_files/PTHR10005.tree:AN89:DROME|FlyBase=FBgn0039932|UniProtKB=D1YSG4;
tree_files/PTHR10005.tree:AN198:DROME|FlyBase=FBgn0085450|UniProtKB=Q00G30;
tree_files/PTHR10009.tree:AN11:DROME|FlyBase=FBgn0004034|UniProtKB=P09957;
tree_files/PTHR10009.tree:AN17:DROME|FlyBase=FBgn0038150|UniProtKB=Q9VFV3;
tree_files/PTHR10009.tree:AN18:DROME|FlyBase=FBgn0038151|UniProtKB=Q9VFV2;
tree_files/PTHR10009.tree:AN19:DROME|FlyBase=FBgn0034856|UniProtKB=Q9W1R0;
```

Will apply and update FTP file tomorrow. Sorry for the false start!

**Comment by dustine32** [comment]
OK @kltm , the tarball is fixed. Specifically, `FlyBase` -> `FB` and `WormBase` -> `WB` in the Panther long IDs.

Lemme know if you have any issues with these files.

**Comment by kltm** [comment]
Noting:
http://data.pantherdb.org/PANTHER14.1/globals/tree_files.tar.gz
http://data.pantherdb.org/PANTHER14.1/globals/names.tab

**Comment by kltm** [comment]
@dustine32 I mean, I think you've fixed this issue, right?

**Comment by kltm** [comment]
To confirm your "forever" patter: `http://data.pantherdb.org/<VERSION>/globals/tree_files.tar.gz`. If so, we'll set that as a variable.
Also, how does one gets GAFs for a version? Those would be required for a full test.

**Comment by dustine32** [comment]
Yup @kltm , that is the forever pattern.

We don't currently publish GAFs for multiple versions in parallel (e.g. each release would have a 13.1 and 14.1 version) nor do we have a way to generate this on demand for users. But, I could do a couple one-off GAF releases of 13.1 and 14.1 for testing. Right now, the regular GAFs are 13.1 so I'll find some alternate location on the FTP to put the 14.1 "test" GAFs.

Does this sound OK?

**Comment by kltm** [comment]
@dustine32 It depends on what we're testing. We're currently pulling everything in *current* for our pipeline. If we are testing whether or not we'll choke on tree size, we can test as-is. If we are testing on data quality or whether we'll choke on GAF size or tree-GAF interaction, we'd need versioned GAFs.

**Comment by kltm** [comment]
@dustine32 If it's useful, I can go ahead and try and test with the new tree release on a new pipeline.

**Comment by kltm** [comment]
Testing on branch: issue-pantherdb-helpdesk-3-new-release

**Comment by kltm** [comment]
Retrying test with a more full load to at least compare timing with normal load.

**Comment by kltm** [comment]
@dustine32 Let's do the 14.1 bits over here: https://github.com/geneontology/pipeline/issues/78
