### ISSUE TITLE
Create a top-level "current" URL that always gives the latest PANTHER data (enhancement)

### ISSUE THREAD

**Issue by kltm** [pantherdb/Helpdesk#4]
Instead of having to know the current PANTHER release and manipulate the URL accordingly, it may be useful to external pipeline users to have a single URL that always points to the latest release. For example, instead of:

http://data.pantherdb.org/PANTHER13.1/books

have:

http://data.pantherdb.org/current/books

This would be useful to ensure that external pipelines consuming PANTHER (e.g. https://github.com/geneontology/amigo/issues/532) are able to always get the latest intended version.

**Comment by kltm** [comment]
This could also be useful if/when PANTHER releases occur at a higher frequency or have a different release cycle than they do now.

**Comment by kltm** [comment]
@dustine32 Sorry to bug you. I'm about to go and start coding hot PANTHER grabs into our pipeline. Should we go ahead with the manual update path, or is this in progress short-term?

**Comment by dustine32** [comment]
Aha! @kltm This guy's up now:
http://data.pantherdb.org/current/

Lemme know if you have any problems with it. Thanks!

**Comment by kltm** [comment]
Cheers!
