### ISSUE TITLE
Download of IDs associated with enriched term

### ISSUE THREAD

**Issue by RLovering** [pantherdb/Helpdesk#6]
Hi 
I have said this many times but to have this documented:
people need to be able to download the list of gp IDs that are enriched associated with each GO term, as a bulk download.
At present I have to open each GO term link to the list of gp IDs. This is not a sensible way to extract the list of gp IDs associated with all of the enriched GO terms.
ie the export results button should export the gp ID list for each term not just the p-values etc

Thanks

Ruth

**Comment by mugitty** [comment]
Functionality has been added to the result page to download user uploaded ids associated with each term.
